### ISSUE TITLE
Can we use this with CRA?

### ISSUE THREAD

**Issue by vadhe** [r17x/babel-plugin-react-suspense#27]
**Describe the bug**
it seems does not work with create-react-app

**To Reproduce**

we can see the code here 
[code](https://stackblitz.com/edit/react-sceg6o?file=src%2FApp.js)

**Comment by r17x** [comment]
@vadhe This is known issue, I don't have any idea to handle this issue. 

FYI, overall platforms like stackblitz or codesandbox. This library doesn't work correctly. 

I will investigated as soon as possible. But, if you interested, I think you can run with cra in you local machine

thanks
